# Generated by Django 4.2.4 on 2023-09-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sd',
        ),
    ]
